version: '3.8'
services:
  backend:
    build:
      context: .                # ← Contexte au niveau racine
      dockerfile: backend/Dockerfile
    volumes:
      - ./models:/app/models
    ports:
      - "5001:5000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
networks:
  sentiment-network:
    driver: bridge
