name: Evaluate Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    needs: test  # Depends on the test workflow

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run evaluation
      run: |
        python -m backend.best_model

    - name: Check metrics
      run: |
        if [ -f "metrics.txt" ]; then
          accuracy=$(grep "Accuracy" metrics.txt | awk '{print $2}')
          echo "Model Accuracy: $accuracy"
          if (( $(echo "$accuracy < 0.7" | bc -l) )); then
            echo "Model accuracy is below 70%, failing the workflow."
            exit 1
          fi
        else
          echo "metrics.txt not found!"
          exit 1
        fi

    - name: Upload metrics
      uses: actions/upload-artifact@v3
      with:
        name: metrics
        path: metrics.txt
